### ISSUE TITLE
VLC needs an update

### ISSUE THREAD

**Issue by erikas-taroza** [alexmercerind/dart_vlc#302]
Hello.

I am using this library for my project. I ran into a bug with the VLC version (3.0.9.2) that this library is using. It does not occur in the latest version (3.0.17.4). I tried forking this repo and updating the VLC 7z and libvlcpp zip in \bin\ but something is not working. Can you please update the dependency or at least create docs for how to do it? Thank you.

**Comment by erikas-taroza** [comment]
I figured out how to update the VLC dependency. Here are the steps I took in case anyone is running into the same problem:

1. Fork this repository and clone to your computer.
2. Download [VLC 7z.](https://download.videolan.org/pub/videolan/vlc/last/win64) You want the 7z file of VLC in 64bit.
3. I am not sure if this is necessary, but I did it anyways: download [LibVLCPP](https://code.videolan.org/videolan/libvlcpp)
4. In the clone go to the bin folder.
5. Replace the contents of libvlcpp and vlc .zips with the contents of the .zips you downloaded above. Make sure all the names are matching (.zip file names and content names).
6. Uploaded changes to GitHub.
7. Add this to your pubspec.yaml:
```yaml
dependencies:
  dart_vlc:
      git:
        url: https://github.com/erikas-taroza/dart_vlc.git # Url to the repository
        ref: e661980 # Commit hash
```
If you want, you can use my repository which updated VLC to version 3.0.17.4 and libvlcpp to commit 0c7d3968.
