### ISSUE TITLE
autoStart: false working in .0.0.6 and not .0.0.7

### ISSUE THREAD

**Issue by syleishere** [alexmercerind/dart_vlc#64]
`      await desktopPlayer!.open(new Playlist(medias: medias, playlistMode: PlaylistMode.loop), autoStart: false);
`
false is not honored when testing on windows 10 on .0.0.7, something got changed from .0.0.6

**Comment by alexmercerind** [comment]
I cannot confirm what you said, it is working flawlessly.

**Comment by alexmercerind** [comment]
P.S. Use git repository version.

**Comment by Zarainia** [comment]
I am also experiencing this with: `sound_player.open(media, autoStart: false))` when playing some sound. I switched to the git repository version and ran pub get and upgrade and still have this problem. 

```yaml
dart_vlc:
    git:
      url: https://github.com/alexmercerind/dart_vlc.git
```
